language: ruby
os:
  - linux
  - osx
rvm:
  - 2.1.3
  - 2.3.4
  - 2.4.1
  - jruby-9.1.9.0
matrix:
  exclude:
    - rvm: 2.1.3
      os: osx
    - rvm: jruby-9.1.9.0
      os: osx
script:
 - "bundle exec rake test"
